# Build input plugins

# nfdump
- name: Build nfdump input plugin
  command: >
    {{ item }}
    chdir={{ build.dir }}/plugins/input/nfdump
    creates=/usr/local/share/ipfixcol/plugins/ipfixcol-nfdump-input.so
  with_items: "{{ build.cmds }}"
  tags: nfdump-input

# udp_cpg - requires libcpg not available fedora and centos repos
#- name: Build UDP CPG input plugin
#  command: >
#    {{ item }}
#    chdir={{ build.dir }}/plugins/input/udp_cpg
#    creates=/usr/local/share/ipfixcol/plugins/ipfixcol-udp_cpg-input.so
#  with_items: "{{ build.cmds }}"
#  tags: udp_cpg