# Tools

# fbitconvert
- name: Build fbitconvert tool
  command: >
    {{ item }}
    chdir={{ build.dir }}/tools/fbitconvert
    creates=/usr/local/bin/fbitconvert
  with_items: "{{ build.cmds }}"
  tags: fbitconvert

# fbitdump  
- name: Build fbitdump tool
  command: >
    {{ item }}
    chdir={{ build.dir }}/tools/fbitdump
    creates=/usr/local/bin/fbitdump
  with_items: "{{ build.cmds }}"
  tags: fbitdump

# fbitexpire
- name: Build fbitexpire tool
  command: >
    {{ item }}
    chdir={{ build.dir }}/tools/fbitexpire
    creates=/usr/local/bin/fbitexpire
  with_items: "{{ build.cmds }}"
  tags: fbitexpire

# fbitmerge
- name: Build fbitmerge tool
  command: >
    {{ item }}
    chdir={{ build.dir }}/tools/fbitmerge
    creates=/usr/local/bin/fbitmerge
  with_items: "{{ build.cmds }}"
  tags: fbitmerge

# profilesdaemon
- name: Build profilesdaemon tool
  command: >
    {{ item }}
    chdir={{ build.dir }}/tools/profilesdaemon
    creates=/usr/local/bin/profilesdaemon
  with_items: "{{ build.cmds }}"
  tags: profilesdaemon